version: "3"
services:
  app:
    build: .
    image: ghcr.io/jswny/factorial
    container_name: factorial
    environment:
      - DISCORD_BOT_TOKEN
      - DISCORD_WEBHOOK_ID
      - DISCORD_WEBHOOK_TOKEN
