version: "3"
services:
  db:
    image: postgres:13.1-alpine
    container_name: factorial-db
    volumes:
      - ${PWD}/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=factorial_prod
  migrate:
    image: ghcr.io/jswny/factorial
    container_name: factorial-migrate
    depends_on:
      - db
    command: eval "Factorial.Release.migrate"
    environment:
      - DATABASE_HOSTNAME=factorial-db
      - DISCORD_BOT_TOKEN
      - DISCORD_WEBHOOK_ID
      - DISCORD_WEBHOOK_TOKEN
  app:
    build: .
    image: ghcr.io/jswny/factorial
    container_name: factorial
    depends_on:
      - db
      - migrate
    environment:
      - DATABASE_HOSTNAME=factorial-db
      - DISCORD_BOT_TOKEN
      - DISCORD_WEBHOOK_ID
      - DISCORD_WEBHOOK_TOKEN
      - COMMAND_PREFIX
